---
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

resources:
  requests:
    cpu: 150m
    memory: 100Mi

rbac:
  create: true

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/instance: sqlproxy
        app.kubernetes.io/name: gcloud-sqlproxy

podDisruptionBudget: |
  maxUnavailable: 0