---
replicasCount: 3

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

rbac:
  create: true

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      app.kubernetes.io/instance: sqlproxy
      app.kubernetes.io/name: gcloud-sqlproxy
