---
defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: make lint | tee /tmp/lint.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Test" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/lint.log)\`\`\`" \
            notify-job-failure.sh
  dev:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: jendevops1
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK
          command: |
            apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
      - run: activate-gcloud-account.sh
      - deploy:
          name: Deploy to development cluster
          command: make dev | tee /tmp/deploy.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Deploy" \
            EXTRA_TEXT="\`\`\`
            $(cat /tmp/deploy.log)
            \`\`\`" \
            notify-job-failure.sh
      - run: |
          TYPE="Deploy" \
          EXTRA_TEXT="\`\`\`$(make history)\`\`\`" \
          notify-job-success.sh
  prod:
    <<: *defaults
    environment:
      GOOGLE_PROJECT_ID: planet4-production
    steps:
      - checkout
      - run: activate-gcloud-account.sh
      - deploy:
          name: Deploy to production cluster
          command: make prod | tee /tmp/deploy.log
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Deploy" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/deploy.log)\`\`\`" \
            notify-job-failure.sh
      - run: |
          TYPE="Deploy" \
          EXTRA_TEXT="\`\`\`$(make history)\`\`\`" \
          notify-job-success.sh

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - dev:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - develop
      - prod:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - master
