---

  ## SQL connection settings
  ##
cloudsql:
  ## PostgreSQL/MySQL instances:
  ## update with your GCP project, the region of your Cloud SQL instance
  ## and the name of your Cloud SQL instance
  ## PostgreSQL port 5432 or MySQL port 3306, or other port you set for your SQL instance.
  ## Use different ports for different instances.
  instances:
    # GCP instance name.
  - instance: "pg-sqlproxy"
    # Optional abbreviation used to override the truncated instance name if the
    # 15 character instance name prefix is not unique for use as a port
    # identifier.
    instanceShortName: ""
    # GCP project where the instance exists.
    project: "$(DEV_PROJECT)"
    # GCP region where the instance exists.
    region: "$(DEV_ZONE)"
    # Port number for the proxy to expose for this instance.
    port: 5432


    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 150Mi
        cpu: 150m

    ## Node selector
    nodeSelector: {}
